name: jupyter-autogen

services:
  jupyter-autogen:
    build:
      context: .
      dockerfile: ./jupyter-lab.dockerfile
    ports:
      - "8888:8888"
    networks:
      - internal_network
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./configs/jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py
    env_file:
      - .env

networks:
  internal_network:


